version: "3"

services:
  db-service:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: retmix
      POSTGRES_USER: retmix
      POSTGRES_PASSWORD: retmix
    ports:
      - "5432:5432"