version: "3"
services:
  project:
    build:
      context: ../..
      dockerfile: .deploy/app/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - services
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: retmix
      POSTGRES_USER: retmix
      POSTGRES_PASSWORD: retmix
    ports:
      - "5432:5432"
    networks:
      - services

networks:
  services:
    driver: bridge